name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages-develop # Saat kamu push ke branch develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages-develop # Checkout source dari develop branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23" # atau sesuai versi Node yang kamu pakai

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: CI='' npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Sesuaikan dengan output build kamu
          publish_branch: gh-pages # Ini tujuan deploy GitHub Pages
