name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages-develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Penting buat peaceiris/actions-gh-pages

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # atau versi yang cocok dengan project kamu

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }} # Ganti dari GITHUB_TOKEN ke token custom kamu
          publish_dir: ./build
          publish_branch: gh-pages
